version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword      # Password untuk root MySQL
      MYSQL_DATABASE: bigproject            # Nama database
      MYSQL_USER: gms                      # Username untuk MySQL
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"                        # Port untuk MySQL
    volumes:
      - mysql-data:/var/lib/mysql          # Menyimpan data MySQL agar persisten
    networks:
      - backend

  web:
    build: .
    ports:
      - "8000:8000"                        # Port untuk FastAPI
    depends_on:
      - db                                 # Web service menunggu database siap
    environment:
      DATABASE_URL: "mysql+pymysql://gms:password@db:3307/bigproject" # Connection string ke MySQL
      OPENAI_API_KEY: "sk-"
    networks:
      - backend
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"                          # Akses phpMyAdmin di http://localhost:8080
    environment:
      PMA_HOST: db                         # Host database MySQL
      PMA_PORT: 3307                       # Port database MySQL
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge