version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: bigproject
      MYSQL_USER: gms
      MYSQL_PASSWORD: gmspassword  # Tambahkan password untuk user gms
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql
    
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+pymysql://gms:gmspassword@db:3307/bigproject"
      OPENAI_API_KEY: "sk-"
    # command: ["sh", "-c", "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000"]
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3307

volumes:
  mysql-data: